name: ${PROJECT_NAME}

services:
  db:
    image: postgres:17-alpine
    container_name: ${PROJECT_NAME}-db
    volumes:
      - pf-data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    networks:
      - pf-net

  backend:
    image: botthice/preflight-project-backend:latest
    container_name: ${PROJECT_NAME}-backend
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${PROJECT_NAME}-db
    depends_on:
      - db
    networks:
      - pf-net

  frontend:
    image: botthice/preflight-project-frontend
    container_name: ${PROJECT_NAME}-frontend
    ports: 
      - ${FRONT_END_PORT}:${FRONT_END_PORT}
    environment:
      - FRONT_END_PORT=${FRONT_END_PORT}
      - BACK_END_URL=http://${PROJECT_NAME}-backend:3000
    networks:
      - pf-net
volumes:
  pf-data:
    name: ${PROJECT_NAME}-pf-data
networks:
  pf-net:
    name: ${PROJECT_NAME}-pf-net